<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html>
<head>
    <title>OWASP ZAP Scan Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f9f9f9; }
        h1 { color: #2c3e50; }
        .summary { background: #ecf0f1; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; background: white; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #2980b9; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .high { background-color: #e74c3c; color: white; }
        .medium { background-color: #f39c12; color: white; }
        .low { background-color: #f1c40f; color: black; }
        .info { background-color: #3498db; color: white; }
    </style>
</head>
<body>
    <h1>OWASP ZAP Baseline Scan Report</h1>
    <div class="summary">
        <p><strong>Site:</strong> <xsl:value-of select="//site/@name"/></p>
        <p><strong>Scanned on:</strong> <xsl:value-of select="//@generated"/></p>
    </div>

    <h2>Alerts Summary</h2>
    <table>
        <tr>
            <th>Risk Level</th>
            <th>Alert Name</th>
            <th>Instances</th>
            <th>Description</th>
        </tr>
        <xsl:for-each select="//alertitem">
            <xsl:variable name="risk">
                <xsl:choose>
                    <xsl:when test="riskcode = 3">high</xsl:when>
                    <xsl:when test="riskcode = 2">medium</xsl:when>
                    <xsl:when test="riskcode = 1">low</xsl:when>
                    <xsl:otherwise>info</xsl:otherwise>
                </xsl:choose>
            </xsl:variable>
            <tr class="{$risk}">
                <td><xsl:value-of select="riskdesc"/></td>
                <td><xsl:value-of select="alert"/></td>
                <td><xsl:value-of select="count"/></td>
                <td><xsl:value-of select="desc"/></td>
            </tr>
        </xsl:for-each>
    </table>

    <hr/>
    <footer>
        <p>Generated by <strong>OWASP ZAP</strong> via Jenkins</p>
    </footer>
</body>
</html>
</xsl:template>
</xsl:stylesheet>