<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Trivy Scan Report - {{ .ArtifactName }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f4f4f4; }
        h1 { color: #2c3e50; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; background: white; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .critical { background-color: #e74c3c; color: white; }
        .high { background-color: #e67e22; color: white; }
        .medium { background-color: #f1c40f; }
        .low { background-color: #95a5a6; }
        .unknown { background-color: #7f8c8d; }
        .summary { background: #ecf0f1; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
    </style>
</head>
<body>
    <h1>Trivy Vulnerability Scan Report</h1>
    <div class="summary">
        <p><strong>Image:</strong> <code>{{ .ArtifactName }}</code></p>
        <p><strong>Scanned on:</strong> {{ now }}</p>
        <p><strong>OS:</strong> {{ if .OS }} {{ .OS.Family }} {{ .OS.Name }} {{ end }}</p>
    </div>

    {{ range .Results }}
        {{ if .Vulnerabilities }}
            <h2>{{ .Target }} ({{ len .Vulnerabilities }} vulnerabilities)</h2>
            <table>
                <tr>
                    <th>Vulnerability ID</th>
                    <th>Severity</th>
                    <th>Package</th>
                    <th>Installed</th>
                    <th>Fixed In</th>
                    <th>Title</th>
                </tr>
                {{ range .Vulnerabilities }}
                <tr class="{{ .Severity | lower }}">
                    <td><a href="https://nvd.nist.gov/vuln/detail/{{ .VulnerabilityID }}" target="_blank">{{ .VulnerabilityID }}</a></td>
                    <td>{{ .Severity }}</td>
                    <td>{{ .PkgName }}</td>
                    <td>{{ .InstalledVersion }}</td>
                    <td>{{ if .FixedVersion }}{{ .FixedVersion }}{{ else }}—{{ end }}</td>
                    <td>{{ .Title }}</td>
                </tr>
                {{ end }}
            </table>
        {{ else }}
            <h2>{{ .Target }}</h2>
            <p>No vulnerabilities found.</p>
        {{ end }}
    {{ else }}
        <h2>No results found</h2>
    {{ end }}

    <hr>
    <footer>
        <p>Generated by <strong>Trivy</strong> on {{ now }}</p>
    </footer>
</body>
</html>